{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-entrypoint
  labels:
    {{- include "tpl.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
    #!/bin/sh
    set -e
    
    echo "Starting PostgreSQL with custom entrypoint..."
    
    mkdir -p "$PGDATA"
    mkdir -p /var/run/postgresql
    chown -R postgres:postgres /var/run/postgresql 2>/dev/null || true
    
    if [ ! -s "$PGDATA/PG_VERSION" ]; then
      echo "Initializing PostgreSQL database..."
      
      echo "$POSTGRES_PASSWORD" > /tmp/pwfile
      
      su-exec postgres initdb \
        -D "$PGDATA" \
        --username="$POSTGRES_USER" \
        --pwfile=/tmp/pwfile \
        --auth-local=trust \
        --auth-host=md5 \
        --encoding=UTF8 \
        --locale=en_US.utf8 \
        --data-checksums
      
      rm /tmp/pwfile
      
      echo "host all all all md5" >> "$PGDATA/pg_hba.conf"
      echo "listen_addresses='*'" >> "$PGDATA/postgresql.conf"
      
      su-exec postgres pg_ctl -D "$PGDATA" -o "-c listen_addresses=''" -w start
      su-exec postgres psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -c "CREATE DATABASE \"$POSTGRES_DB\";"
      su-exec postgres pg_ctl -D "$PGDATA" -m fast -w stop
      
      echo "PostgreSQL initialized successfully!"
    fi
    
    echo "Starting PostgreSQL server..."
    exec su-exec postgres postgres
{{- end }}