{{- if .Values.Secrets }}
{{- $hasValues := false }}
{{- range $key, $value := .Values.Secrets }}
  {{- if $value }}
    {{- $hasValues = true }}
  {{- end }}
{{- end }}
{{- if $hasValues }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | default (printf "%s-secret" .Release.Name) | quote }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
type: Opaque
data:
  {{- range $key, $value := .Values.Secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}